// 知识库管理工作区：浏览器文件导入、版本审核、索引维护和评估门禁展示。
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { UseMutationResult } from '@tanstack/react-query'
import { BookOpen, Check, FilePlus2, RotateCw, ShieldAlert, XCircle } from 'lucide-react'
import { ChangeEvent, useMemo, useRef, useState } from 'react'
import { api, AuthorityLevel, KnowledgeImportRequest, KnowledgeMutation, KnowledgePreview, KnowledgeStatus, KnowledgeType } from './api'

const statusLabel: Record<KnowledgeStatus, string> = { draft: '草稿', approved: '已发布', disabled: '已停用', superseded: '已替代' }

const emptyImport: KnowledgeImportRequest = {
  file_name: '', content: '', knowledge_id: '', title: '', knowledge_type: 'runbook', authority: 'medium', source_name: '', source_location: '', language: 'zh-CN', summary: '', version: 1, ack_risk: false,
}

export function KnowledgeManagement() {
  // active 门禁只读展示，前端不具备修改或绕过评估结果的能力。
  const client = useQueryClient()
  const [status, setStatus] = useState('')
  const [selected, setSelected] = useState('')
  const [form, setForm] = useState<KnowledgeImportRequest>(emptyImport)
  const [previewOpen, setPreviewOpen] = useState(false)
  const list = useQuery({ queryKey: ['knowledge', status], queryFn: () => api.knowledge(status) })
  const detail = useQuery({ queryKey: ['knowledge-detail', selected], queryFn: () => api.knowledgeDetail(selected), enabled: Boolean(selected) })
  const evaluation = useQuery({ queryKey: ['knowledge-evaluation'], queryFn: api.knowledgeEvaluation })
  const refresh = () => { client.invalidateQueries({ queryKey: ['knowledge'] }); client.invalidateQueries({ queryKey: ['knowledge-detail', selected] }); client.invalidateQueries({ queryKey: ['knowledge-evaluation'] }) }
  const preview = useMutation({ mutationFn: () => api.previewKnowledge(form) })
  const importDraft = useMutation({ mutationFn: () => api.importKnowledge(form), onSuccess: value => { setSelected(value.version_id.split(':v')[0]); setPreviewOpen(false); setForm(emptyImport); preview.reset(); refresh() } })
  const approve = useMutation({ mutationFn: ({ id, reviewer }: { id: string; reviewer: string }) => api.approveKnowledge(id, reviewer), onSuccess: refresh })
  const disable = useMutation({ mutationFn: ({ id, actor, reason }: { id: string; actor: string; reason: string }) => api.disableKnowledge(id, actor, reason), onSuccess: refresh })
  const reindex = useMutation({ mutationFn: ({ id, force }: { id: string; force: boolean }) => api.reindexKnowledge(id, force), onSuccess: refresh })
  const counts = useMemo(() => ({ approved: list.data?.items.filter(item => item.status === 'approved').length ?? 0, draft: list.data?.items.filter(item => item.status === 'draft').length ?? 0 }), [list.data])
  const update = <K extends keyof KnowledgeImportRequest>(key: K, value: KnowledgeImportRequest[K]) => setForm(current => ({ ...current, [key]: value }))
  // File API 只读取用户选择的文本；不发送或保存浏览器本地绝对路径。
  const chooseFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { update('file_name', file.name); update('content', String(reader.result ?? '')); if (!form.title) update('title', file.name.replace(/\.[^.]+$/, '')); if (!form.knowledge_id) update('knowledge_id', file.name.replace(/\.[^.]+$/, '').toLowerCase().replace(/[^a-z0-9._:-]+/g, '.').replace(/^\.+|\.+$/g, '')) }; reader.readAsText(file, 'utf-8') }
  return <section className="knowledge-workspace">
    <div className="knowledge-head"><div><h1>知识库</h1><p>审核后发布的知识用于补充 TCP 诊断，不替代当前报文证据。</p></div><button className="command" onClick={() => setPreviewOpen(true)}><FilePlus2 />导入知识</button></div>
    <div className="knowledge-metrics"><Metric label="已发布" value={String(counts.approved)} /><Metric label="草稿" value={String(counts.draft)} /><Metric label="Active 门禁" value={evaluation.data?.active_gate_passed ? '已通过' : '未通过'} tone={evaluation.data?.active_gate_passed ? 'good' : 'warn'} /><Metric label="当前模式" value={evaluation.data ? `${evaluation.data.effective_mode}` : '读取中'} /></div>
    <div className="knowledge-layout"><aside className="knowledge-list"><div className="knowledge-filter"><b>知识条目</b><select value={status} onChange={event => { setStatus(event.target.value); setSelected('') }} aria-label="知识状态筛选"><option value="">全部状态</option>{Object.entries(statusLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div>{list.isLoading ? <div className="loading">正在读取知识</div> : list.error ? <Error value={list.error} /> : list.data?.items.map(item => <button key={item.knowledge_id} className={`knowledge-item ${selected === item.knowledge_id ? 'active' : ''}`} onClick={() => setSelected(item.knowledge_id)}><span><b>{item.title}</b><small>{item.knowledge_id}</small></span><i className={`knowledge-status ${item.status}`}>{statusLabel[item.status]}</i></button>)}</aside>
      <div className="knowledge-detail">{detail.isLoading ? <div className="loading">正在读取版本</div> : detail.error ? <Error value={detail.error} /> : detail.data ? <KnowledgeDetailPanel detail={detail.data} approve={approve} disable={disable} reindex={reindex} /> : <div className="empty"><BookOpen /><p>从左侧选择知识查看版本与审核操作</p></div>}</div>
      <aside className="evaluation-panel"><h2>评估状态</h2>{evaluation.error ? <Error value={evaluation.error} /> : <><p><b>{evaluation.data?.active_gate_passed ? '门禁已通过' : '门禁未通过'}</b><span>请求模式：{evaluation.data?.requested_mode ?? '-'}</span></p>{evaluation.data?.last_report ? <dl>{Object.entries(evaluation.data.last_report).filter(([key]) => ['case_count', 'recall_at_5', 'citation_accuracy', 'applicability_accuracy', 'p95_latency_seconds', 'production_ready'].includes(key)).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl> : <small>尚无评估记录。使用 pkm knowledge evaluate 写入正式评估报告。</small>}</>}</aside></div>
    {previewOpen && <ImportDialog form={form} update={update} chooseFile={chooseFile} preview={preview} submit={importDraft} close={() => { setPreviewOpen(false); preview.reset() }} />}
  </section>
}

function KnowledgeDetailPanel({ detail, approve, disable, reindex }: { detail: Awaited<ReturnType<typeof api.knowledgeDetail>>; approve: UseMutationResult<KnowledgeMutation, Error, { id: string; reviewer: string }, unknown>; disable: UseMutationResult<KnowledgeMutation, Error, { id: string; actor: string; reason: string }, unknown>; reindex: UseMutationResult<KnowledgeMutation, Error, { id: string; force: boolean }, unknown> }) {
  const [operator, setOperator] = useState('local-reviewer')
  const [reason, setReason] = useState('内容过期或不再适用')
  return <><div className="detail-title"><div><span className={`knowledge-status ${detail.document.status}`}>{statusLabel[detail.document.status]}</span><h2>{detail.document.title}</h2><p>{detail.document.summary || '无摘要'}</p></div><small>{detail.document.knowledge_id} · {detail.document.knowledge_type} · {detail.document.authority}</small></div><div className="version-list">{detail.versions.map(version => <article key={version.version_id}><div><b>V{version.version_number}</b><span>{statusLabel[version.status]} · {version.chunk_count} 个切片 · {version.source_name}</span><small>{version.version_id}</small></div><div className="version-actions">{version.status === 'draft' && <button className="primary" onClick={() => approve.mutate({ id: version.version_id, reviewer: operator })} disabled={approve.isPending}><Check />审核发布</button>}{version.status === 'approved' && <button className="secondary danger" onClick={() => disable.mutate({ id: version.version_id, actor: operator, reason })} disabled={disable.isPending}><XCircle />停用</button>}<button className="secondary" onClick={() => reindex.mutate({ id: version.version_id, force: true })} disabled={reindex.isPending}><RotateCw />重建索引</button></div></article>)}</div><div className="knowledge-operator"><label>审核人/操作者<input value={operator} onChange={event => setOperator(event.target.value)} /></label><label>停用原因<input value={reason} onChange={event => setReason(event.target.value)} /></label></div>{approve.error && <Error value={approve.error} />}{disable.error && <Error value={disable.error} />}{reindex.error && <Error value={reindex.error} />}</>
}

function ImportDialog({ form, update, chooseFile, preview, submit, close }: { form: KnowledgeImportRequest; update: <K extends keyof KnowledgeImportRequest>(key: K, value: KnowledgeImportRequest[K]) => void; chooseFile: (event: ChangeEvent<HTMLInputElement>) => void; preview: UseMutationResult<KnowledgePreview, Error, void, unknown>; submit: UseMutationResult<KnowledgeMutation, Error, void, unknown>; close: () => void }) {
  const fileInput = useRef<HTMLInputElement>(null)
  const ready = Boolean(form.file_name && form.content && form.knowledge_id && form.title && form.source_name)
  return <div className="modal-backdrop" role="presentation"><div className="modal knowledge-import" role="dialog" aria-modal="true" aria-label="导入知识"><div className="modal-head"><h2>导入知识草稿</h2><button className="icon" onClick={close} aria-label="关闭"><XCircle /></button></div><div className="knowledge-file-picker"><span>知识文件</span><input ref={fileInput} className="visually-hidden" type="file" accept=".md,.markdown,.txt,.json,text/plain,application/json" onChange={chooseFile} /><button type="button" className="secondary" onClick={() => fileInput.current?.click()}><FilePlus2 />选择本地文件</button><small>{form.file_name || '支持 .md、.markdown、.txt 和 .json 文件'}</small></div><div className="import-grid"><label>知识 ID<input value={form.knowledge_id} onChange={event => update('knowledge_id', event.target.value)} /></label><label>标题<input value={form.title} onChange={event => update('title', event.target.value)} /></label><label>类型<select value={form.knowledge_type} onChange={event => update('knowledge_type', event.target.value as KnowledgeType)}><option value="standard">标准</option><option value="vendor">厂商资料</option><option value="runbook">运行手册</option><option value="case">历史案例</option></select></label><label>权威性<select value={form.authority} onChange={event => update('authority', event.target.value as AuthorityLevel)}><option value="high">高</option><option value="medium_high">中高</option><option value="medium">中</option><option value="low">低</option></select></label><label>来源名称<input value={form.source_name} onChange={event => update('source_name', event.target.value)} /></label><label>来源章节<input value={form.source_location} onChange={event => update('source_location', event.target.value)} /></label></div><label>摘要<textarea value={form.summary} onChange={event => update('summary', event.target.value)} /></label><div className="modal-actions"><button className="secondary" disabled={!ready || preview.isPending} onClick={() => preview.mutate()}>{preview.isPending ? '正在预览' : '生成预览'}</button>{preview.data && <button className="primary" disabled={submit.isPending || (preview.data.requires_risk_acknowledgement && !form.ack_risk)} onClick={() => submit.mutate()}>{submit.isPending ? '正在保存' : '保存草稿'}</button>}</div>{preview.error && <Error value={preview.error} />}{preview.data && <div className="import-preview"><p><b>{preview.data.version_id}</b> · {preview.data.chunk_count} 个切片</p>{preview.data.requires_risk_acknowledgement && <label className="risk"><ShieldAlert />检测到风险内容<input type="checkbox" checked={form.ack_risk} onChange={event => update('ack_risk', event.target.checked)} />我已审核并确认导入</label>}{preview.data.chunks.map(chunk => <details key={chunk.chunk_id}><summary>{chunk.heading_path.join(' / ') || chunk.chunk_id}</summary><p>{chunk.content}</p></details>)}</div>}</div></div>
}

function Metric({ label, value, tone = '' }: { label: string; value: string; tone?: string }) { return <div className={`metric ${tone}`}><label>{label}</label><b>{value}</b></div> }
function Error({ value }: { value: Error }) { return <div className="error-notice"><b>{value.message}</b></div> }
